In [37]:
import pandas as pd

## Question 1 - 3

In [38]:
belts = ('white', 'blue', 'purple', 'brown', 'black')
# belts[0] = 'red'
# TypeError: 'tuple' object does not support item assignment
# meaning - tuple is an immutable object that does not support item assignment

## Question 4-6

In [39]:
anime = pd.DataFrame({'title': ['Attack on Titan', 'One Piece', 'Death Note', 'Naruto', 'Jujutsu Kaisen'],
                      'rating': [9.0, 8.9, 9.0, 8.4, 8.6],
                      'episodes': [87, 1100, 37, 720, 47]})
anime

             title  rating  episodes
0  Attack on Titan     9.0        87
1        One Piece     8.9      1100
2       Death Note     9.0        37
3           Naruto     8.4       720
4   Jujutsu Kaisen     8.6        47

In [40]:
anime.shape
# 5 rows 3 columns

(5, 3)

In [41]:
anime.dtypes

title           str
rating      float64
episodes      int64
dtype: object

## Question 7-9

In [42]:
anime.head(3)

             title  rating  episodes
0  Attack on Titan     9.0        87
1        One Piece     8.9      1100
2       Death Note     9.0        37

In [43]:
anime.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   title     5 non-null      str
 1   rating    5 non-null      float64
 2   episodes  5 non-null      int64
dtypes: float64(1), int64(1), str(1)
memory usage: 252.0 bytes

In [44]:
anime.describe()

         rating     episodes
count  5.000000     5.000000
mean   8.780000   398.200000
std    0.268328   486.500462
min    8.400000    37.000000
25%    8.600000    47.000000
50%    8.900000    87.000000
75%    9.000000   720.000000
max    9.000000  1100.000000

In [45]:
ratings = anime['rating']
type(ratings)

pandas.Series

## Question 10-12

In [46]:
meals = pd.DataFrame({
     'meal': ['borshch', 'shawarma','ramen', 'pizza'],
     'calories': [450, 800, 650, 900],
     'protein': [25, 40, 30,35]
})
meals

       meal  calories  protein
0   borshch       450       25
1  shawarma       800       40
2     ramen       650       30
3     pizza       900       35

In [47]:
meals[meals['calories']>700]

       meal  calories  protein
1  shawarma       800       40
3     pizza       900       35

In [48]:
meals['double'] = meals['calories']*2
meals['double']

0     900
1    1600
2    1300
3    1800
Name: double, dtype: int64

## Question 13-15

In [49]:
week = pd.DataFrame({
    'day': ['Mon','Wed', 'Fri'],
    'minutes': [90, 60, 90],
    'sparring': [True, False, True]
})
week

   day  minutes  sparring
0  Mon       90      True
1  Wed       60     False
2  Fri       90      True

In [50]:
week.iloc[0]

day          Mon
minutes       90
sparring    True
Name: 0, dtype: object

In [51]:
week['minutes'].mean()

np.float64(80.0)

In [52]:
week.describe()

         minutes
count   3.000000
mean   80.000000
std    17.320508
min    60.000000
25%    75.000000
50%    90.000000
75%    90.000000
max    90.000000